apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "git-auth-proxy.fullname" . }}
  labels:
    {{- include "git-auth-proxy.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "git-auth-proxy.fullname" . }}
  labels:
    {{- include "git-auth-proxy.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "git-auth-proxy.fullname" . }}
  labels:
    {{- include "git-auth-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "git-auth-proxy.fullname" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "git-auth-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
