apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git-auth-proxy.fullname" . }}
  labels:
    {{- include "git-auth-proxy.labels" . | nindent 4 }}
stringData:
  config.json: {{ required "Config has to be set." .Values.config | quote }}
