image:
  pullPolicy: Never

config: |
  {
    "organizations": [
      {
        "name": "org",
        "provider": "azuredevops",
        "azuredevops": {
          "pat": "foobar"
        },
        "host": "test-nginx",
        "scheme": "http",
        "repositories": [
          {
            "name": "repo",
            "project": "proj",
            "namespaces": ["tenant-1", "tenant-2"]
          }
        ]
      }
    ]
  }
